version: '3.3'
services:
  mhslvl-soap:
    build:
      dockerfile: Dockerfile
    ports:
      - 8081:8081
    env_file:
      - .env

  mhslvl-soap-db:
    image: mysql:latest
    ports:
      - 3308:3306
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
    env_file:
      - .env
    volumes:
      - ./db:/docker-entrypoint-initdb.d